Automatically select db on new connection creation in pool
thefab/tornadis pull request #34
Opened 2016-09-18 13:03 UTC by marrrvin

2016-09-21 07:10 UTC, thefab commented
great ! just a little change proposal

2016-09-21 11:30 UTC, marrrvin commented
Ok. What should I do?

2016-09-21 15:02 UTC, thefab commented on tornadis/pool.py
> +                yield client.call('SELECT', self.db)
can you add a test about the result of the SELECT command and raise a tornado.gen.Return(ClientError("something")) if there is a problem here ?

2016-09-21 15:02 UTC, thefab requested changes

2016-09-21 20:50 UTC, marrrvin commented on tornadis/pool.py
> +                yield client.call('SELECT', self.db)
>raise a tornado.gen.Return(ClientError("something"))
Done.

>can you add a test about the result
I have no idea how to figure out what db is selected right now (

2016-09-25 12:33 UTC, marrrvin commented on tornadis/pool.py
> +                yield client.call('SELECT', self.db)
One more thing.
Please make release after this feature will be merged.

2016-09-25 19:53 UTC, thefab approved these changes

2016-09-25 19:53 UTC, thefab commented
It seems good for me, I merge it

2016-09-25 19:53 UTC, merged

2016-09-25 20:59 UTC, marrrvin commented
Thank you.
Can you make new release, please?

2016-09-26 14:55 UTC, thefab commented
I just moved your db selection code from pool to client object.

Same behaviour but you don't have db property anymore on the pool object (but on the client object)

Can you test it ?

2016-09-26 18:18 UTC, marrrvin commented
Thanks. It works for me.